Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -23,26 +23,26 @@ phases:
     commands:
       - echo "Pushing to ECR..."
       - docker push 758327527391.dkr.ecr.eu-north-1.amazonaws.com/ecr/ci-cd:latest
-
-finally:
-  commands:
-    - echo "DEBUG: Build status code - $CODEBUILD_BUILD_SUCCEEDING"
-    - |
-      if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then
-        MESSAGE="SUCCESS ✅ $CODEBUILD_BUILD_ID"
-      else
-        MESSAGE="FAILURE ❌ $CODEBUILD_BUILD_ID"
-      fi
-      
-      # Force region and add error logging
-      aws sns publish \
-        --topic-arn arn:aws:sns:eu-north-1:758327527391:CodeBuildNotifications \
-        --message "$MESSAGE" \
-        --subject "[$CODEBUILD_BUILD_SUCCEEDING] Build Status" \
-        --region eu-north-1 \
-        2> sns-error.log || echo "SNS publish failed!"
+ 
+  finally:
+    commands:
+      - echo "DEBUG: Build status code - $CODEBUILD_BUILD_SUCCEEDING"
+      - |
+        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then
+          MESSAGE="SUCCESS ✅ $CODEBUILD_BUILD_ID"
+        else
+          MESSAGE="FAILURE ❌ $CODEBUILD_BUILD_ID"
+        fi
         
-    - echo "SNS Error Logs:"
-    - cat sns-error.log
-
-
+        # Force region and add error logging
+        aws sns publish \
+          --topic-arn arn:aws:sns:eu-north-1:758327527391:CodeBuildNotifications \
+          --message "$MESSAGE" \
+          --subject "[$CODEBUILD_BUILD_SUCCEEDING] Build Status" \
+          --region eu-north-1 \
+          2> sns-error.log || echo "SNS publish failed!"
+          
+      - echo "SNS Error Logs:"
+      - cat sns-error.log
+  
+  
